server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.7:3306/starday-os?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: sanyi2019
  hikari:
    maximum-pool-size: 20
    minimum-idle: 10





  redis:
    url: http://192.168.100.7:6379
    password:
    lettuce:
      pool:
        max-wait: -1
    timeout: 100ms

# redis配置l
#  redis:
#    database: 0
#      host: 192.168.100.7
#      port: 6379
#      password:
#     #集群配置
#    #    cluster:
#    #      nodes:
#    #        - 127.0.0.1:6379
#    #        - 127.0.0.1:6380
#    #        - 127.0.0.1:6381
#    #        - 127.0.0.1:6382
#    lettuce: #连接池配置
#      pool:
#        # 连接池中的最大空闲连接 默认8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认0
#        min-idle: 0
#        # 连接池最大连接数 默认8 ，负数表示没有限制
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
#        max-wait: -1
#    timeout: 30000




logging:
  level:
    com.sanyi.stardayweb.mapper: debug

